@projects_build_api_HostAddress = http://localhost:5218

GET {{projects_build_api_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{projects_build_api_HostAddress}}/weatherforecast/
Accept: application/json

###
