packages:
  - apps/*
  - packages/*
  - configs/*

minimumReleaseAge: 1440 # 1 day in minutes
allowBuilds:
  "@parcel/watcher": true
  esbuild: true
  lmdb: true
  msgpackr-extract: true

catalog:
  "@types/node": ^26.1.1
  vite: ^8.1.5
