# Ref: https://github.com/Huachao/vscode-restclient

@urlBase = http://localhost:5004
@urlDemos = {{urlBase}}/api/demos
@contentType = application/json

# ------------------------------------------------------------------------------------- #
### GET throw exception
GET {{urlDemos}}/throw-exception

### GET bad request inline
GET {{urlDemos}}/bad-request-inline
### GET bad request
GET {{urlDemos}}/bad-request
### GET status
GET {{urlDemos}}/status-inline/404

### POST result problem
POST {{urlDemos}}/problem
### POST result validation problem
POST {{urlDemos}}/validation-problem

### GET not found
GET {{urlDemos}}/not-found


# ------------------------------------------------------------------------------------- #
### GET path and query params
GET {{urlDemos}}/get-path-query-params
?qpa=abc
&qpn=123
&qpAry=qpAry1
&qpAry=qpAry2


### POST form data
POST {{urlDemos}}/post-form
Content-Type: application/x-www-form-urlencoded
# Content-Type: multipart/form-data

title=Blog Title
&content=Blog form content...
&completed=false
&priority=2
&otherField=not expected
### POST JSON body
POST {{urlDemos}}/post-json
Content-Type: {{contentType}}

{
	"otherField": "not expected",
	"title": "Blog Title",
	"content": "Blog json content",
	"priority": 5,
	"completed": true
}
### POST JSON body with validation
POST {{urlDemos}}/post-validation
Content-Type: {{contentType}}

{
	"otherField": "not expected",
	# "title": "Blog Title",
	"title": "Blog Title with a lot of extra info",
	"content": "b",
	"priority": 7,
	"completed": true
}


# ------------------------------------------------------------------------------------- #
### GET context user
GET {{urlDemos}}/context-user
