# Ref: https://github.com/Huachao/vscode-restclient

@urlBase = http://localhost:5004
@urlDemos = {{urlBase}}/api/demos
@contentType = application/json

### --------------------------------------------------------------------------------- ###
# GET Exception
{{urlDemos}}/exception


### --------------------------------------------------------------------------------- ###
# GET Not Found
GET {{urlDemos}}/not-found


### --------------------------------------------------------------------------------- ###
# GET path and query params
GET {{urlDemos}}/get-path-query-params
?qpa=abc
&qpn=123
&qpAry=qpAry1
&qpAry=qpAry2


### --------------------------------------------------------------------------------- ###
# POST Form data
POST {{urlDemos}}/post-form
Content-Type: application/x-www-form-urlencoded
# Content-Type: multipart/form-data

title=Blog Title
&content=Blog form content...
&completed=false
&priority=2
&otherField=not expected


### --------------------------------------------------------------------------------- ###
# POST JSON body
POST {{urlDemos}}/post-json
Content-Type: {{contentType}}

{
	"otherField": "not expected",
	"title": "Blog Title",
	"content": "Blog json content",
	"priority": 5,
	"completed": true
}


### --------------------------------------------------------------------------------- ###
# GET context user
GET {{urlDemos}}/context-user
