# Ref: https://github.com/Huachao/vscode-restclient

@urlBase = http://localhost:5003
@urlProjects = {{urlBase}}/api/v1/projects
@contentType = application/json

### --------------------------------------------------------------------------------- ###
# GET projects
GET {{urlProjects}}
ContentType: {{contentType}}


### --------------------------------------------------------------------------------- ###
# GET project by id
@id = UTTX2OU2

GET {{urlProjects}}/{{id}}
Content-Type: {{contentType}}


### --------------------------------------------------------------------------------- ###
# CREATE project
# @name project
POST {{urlProjects}}
Content-Type: {{contentType}}

{
	"name": "Sample Project",
	"description": "Using .http",
	"notes": null,
	"status": "building"
}


### --------------------------------------------------------------------------------- ###
# PUT project by id
PUT  {{urlProjects}}/{{id}}
Content-Type: {{contentType}}

{
	"name": "New name",
	"description": "some project description",
	"notes": "some project notes",
	"status": "complete"
	# "dateCompleted": "2024-12-11",
	# "rating": 4,
	# "recommend": true
}


### --------------------------------------------------------------------------------- ###
# DELETE project by Id
DELETE  {{urlProjects}}/{{id}}
Content-Type: {{contentType}}

