# Ref: https://github.com/Huachao/vscode-restclient

@urlBase = http://localhost:5003
@urlDemos = {{urlBase}}/demos
@contentType = application/json

### --------------------------------------------------------------------------------- ###
# Error
{{urlDemos}}/error

