# Ref: https://github.com/Huachao/vscode-restclient

@urlBase = http://localhost:5003
@urlDemos = {{urlBase}}/demos
@contentType = application/json

### --------------------------------------------------------------------------------- ###
# Error
{{urlDemos}}/error


### --------------------------------------------------------------------------------- ###
# Not Found
GET {{urlDemos}}/test


### --------------------------------------------------------------------------------- ###
# GET demo
GET {{urlDemos}}/obj/123


### --------------------------------------------------------------------------------- ###
# POST demo
POST {{urlDemos}}/obj
Content-Type: {{contentType}}

{
	"id": 123,
	"title": "Blog Title",
	"noField": "noValue"
}
