# Ref: https://github.com/Huachao/vscode-restclient
@urlProjects = http://localhost:5002/api/v1/projects
@contentType = application/json

### --------------------------------------------------------------------------------- ###
# GET all projects
GET {{urlProjects}}
Content-Type: {{contentType}}


### --------------------------------------------------------------------------------- ###
# GET project by id
@id = 52e1b54a

# GET {{urlProjects}}/{{id}}
GET {{urlProjects}}/{{project.response.body.$.id}}
Content-Type: {{contentType}}


### --------------------------------------------------------------------------------- ###
# CREATE project
# @name project
POST {{urlProjects}}
Content-Type: {{contentType}}

{
	"name": "Sample Project",
	"description": "Using .http",
	"notes": null,
	"status": "building"
}


### --------------------------------------------------------------------------------- ###
# CREATE project w/ error
# @name project
POST {{urlProjects}}/error
Content-Type: {{contentType}}

{
	"name": "Erroring Project Input",
	"description": "This invalid project input will fail db constraint validation and return an internal server error response",
	"status": "invalid",
	"rating": 0
}


### --------------------------------------------------------------------------------- ###
# PUT project by id
# PUT {{urlProjects}}/{{id}}
PUT {{urlProjects}}/{{project.response.body.$.id}}
Content-Type: {{contentType}}

{
	"name": "New name",
	"description": "some project description",
	"notes": "some project notes",
	"status": "complete",
	"dateCompleted": "2024-12-11",
	"rating": 4,
	"recommend": true
}


### --------------------------------------------------------------------------------- ###
# DELETE project by Id
# DELETE {{urlProjects}}/{{id}}
DELETE {{urlProjects}}/{{project.response.body.$.id}}
Content-Type: {{contentType}}

